/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RepertorioEnemRouteImport } from './routes/repertorio-enem'
import { Route as RedacaoProntaRouteImport } from './routes/redacao-pronta'
import { Route as RedacaoRouteImport } from './routes/redacao'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as ProvaRealRouteImport } from './routes/prova-real'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PlanoEstudoRouteImport } from './routes/plano-estudo'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PdfsRouteImport } from './routes/pdfs'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimuladoIdRouteImport } from './routes/simulado.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicCronPlanoVencendoRouteImport } from './routes/api/public/cron-plano-vencendo'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioEnemRoute = RepertorioEnemRouteImport.update({
  id: '/repertorio-enem',
  path: '/repertorio-enem',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoProntaRoute = RedacaoProntaRouteImport.update({
  id: '/redacao-pronta',
  path: '/redacao-pronta',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoRoute = RedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaRealRoute = ProvaRealRouteImport.update({
  id: '/prova-real',
  path: '/prova-real',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoEstudoRoute = PlanoEstudoRouteImport.update({
  id: '/plano-estudo',
  path: '/plano-estudo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfsRoute = PdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoIdRoute = SimuladoIdRouteImport.update({
  id: '/simulado/$id',
  path: '/simulado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPlanoVencendoRoute =
  ApiPublicCronPlanoVencendoRouteImport.update({
    id: '/api/public/cron-plano-vencendo',
    path: '/api/public/cron-plano-vencendo',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/pdfs': typeof PdfsRoute
  '/perfil': typeof PerfilRoute
  '/plano-estudo': typeof PlanoEstudoRoute
  '/planos': typeof PlanosRoute
  '/prova-real': typeof ProvaRealRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/redacao': typeof RedacaoRoute
  '/redacao-pronta': typeof RedacaoProntaRoute
  '/repertorio-enem': typeof RepertorioEnemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/simulado/$id': typeof SimuladoIdRoute
  '/api/public/cron-plano-vencendo': typeof ApiPublicCronPlanoVencendoRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/pdfs': typeof PdfsRoute
  '/perfil': typeof PerfilRoute
  '/plano-estudo': typeof PlanoEstudoRoute
  '/planos': typeof PlanosRoute
  '/prova-real': typeof ProvaRealRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/redacao': typeof RedacaoRoute
  '/redacao-pronta': typeof RedacaoProntaRoute
  '/repertorio-enem': typeof RepertorioEnemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/simulado/$id': typeof SimuladoIdRoute
  '/api/public/cron-plano-vencendo': typeof ApiPublicCronPlanoVencendoRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/pdfs': typeof PdfsRoute
  '/perfil': typeof PerfilRoute
  '/plano-estudo': typeof PlanoEstudoRoute
  '/planos': typeof PlanosRoute
  '/prova-real': typeof ProvaRealRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/redacao': typeof RedacaoRoute
  '/redacao-pronta': typeof RedacaoProntaRoute
  '/repertorio-enem': typeof RepertorioEnemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/simulado/$id': typeof SimuladoIdRoute
  '/api/public/cron-plano-vencendo': typeof ApiPublicCronPlanoVencendoRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aulas'
    | '/auth'
    | '/dashboard'
    | '/minha-assinatura'
    | '/pdfs'
    | '/perfil'
    | '/plano-estudo'
    | '/planos'
    | '/prova-real'
    | '/questoes'
    | '/ranking'
    | '/redacao'
    | '/redacao-pronta'
    | '/repertorio-enem'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/simulado/$id'
    | '/api/public/cron-plano-vencendo'
    | '/api/public/mp-webhook'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aulas'
    | '/auth'
    | '/dashboard'
    | '/minha-assinatura'
    | '/pdfs'
    | '/perfil'
    | '/plano-estudo'
    | '/planos'
    | '/prova-real'
    | '/questoes'
    | '/ranking'
    | '/redacao'
    | '/redacao-pronta'
    | '/repertorio-enem'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/simulado/$id'
    | '/api/public/cron-plano-vencendo'
    | '/api/public/mp-webhook'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/aulas'
    | '/auth'
    | '/dashboard'
    | '/minha-assinatura'
    | '/pdfs'
    | '/perfil'
    | '/plano-estudo'
    | '/planos'
    | '/prova-real'
    | '/questoes'
    | '/ranking'
    | '/redacao'
    | '/redacao-pronta'
    | '/repertorio-enem'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/simulado/$id'
    | '/api/public/cron-plano-vencendo'
    | '/api/public/mp-webhook'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasRoute: typeof AulasRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  PdfsRoute: typeof PdfsRoute
  PerfilRoute: typeof PerfilRoute
  PlanoEstudoRoute: typeof PlanoEstudoRoute
  PlanosRoute: typeof PlanosRoute
  ProvaRealRoute: typeof ProvaRealRoute
  QuestoesRoute: typeof QuestoesRoute
  RankingRoute: typeof RankingRoute
  RedacaoRoute: typeof RedacaoRoute
  RedacaoProntaRoute: typeof RedacaoProntaRoute
  RepertorioEnemRoute: typeof RepertorioEnemRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SimuladoIdRoute: typeof SimuladoIdRoute
  ApiPublicCronPlanoVencendoRoute: typeof ApiPublicCronPlanoVencendoRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio-enem': {
      id: '/repertorio-enem'
      path: '/repertorio-enem'
      fullPath: '/repertorio-enem'
      preLoaderRoute: typeof RepertorioEnemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao-pronta': {
      id: '/redacao-pronta'
      path: '/redacao-pronta'
      fullPath: '/redacao-pronta'
      preLoaderRoute: typeof RedacaoProntaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao': {
      id: '/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof RedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova-real': {
      id: '/prova-real'
      path: '/prova-real'
      fullPath: '/prova-real'
      preLoaderRoute: typeof ProvaRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-estudo': {
      id: '/plano-estudo'
      path: '/plano-estudo'
      fullPath: '/plano-estudo'
      preLoaderRoute: typeof PlanoEstudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfs': {
      id: '/pdfs'
      path: '/pdfs'
      fullPath: '/pdfs'
      preLoaderRoute: typeof PdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado/$id': {
      id: '/simulado/$id'
      path: '/simulado/$id'
      fullPath: '/simulado/$id'
      preLoaderRoute: typeof SimuladoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-plano-vencendo': {
      id: '/api/public/cron-plano-vencendo'
      path: '/api/public/cron-plano-vencendo'
      fullPath: '/api/public/cron-plano-vencendo'
      preLoaderRoute: typeof ApiPublicCronPlanoVencendoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasRoute: AulasRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  PdfsRoute: PdfsRoute,
  PerfilRoute: PerfilRoute,
  PlanoEstudoRoute: PlanoEstudoRoute,
  PlanosRoute: PlanosRoute,
  ProvaRealRoute: ProvaRealRoute,
  QuestoesRoute: QuestoesRoute,
  RankingRoute: RankingRoute,
  RedacaoRoute: RedacaoRoute,
  RedacaoProntaRoute: RedacaoProntaRoute,
  RepertorioEnemRoute: RepertorioEnemRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SimuladoIdRoute: SimuladoIdRoute,
  ApiPublicCronPlanoVencendoRoute: ApiPublicCronPlanoVencendoRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
