INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 31, 'LINGUAGENS', 'Em tempos de feed infinito, o leitor não escolhe apenas o que ver. Parte do conteúdo chega filtrada por sistemas que destacam, silenciam e reorganizam publicações conforme hábitos anteriores de navegação.

A ideia central do texto é que:', 'a internet garante neutralidade total na circulação de informações', 'o usuário lê apenas conteúdos produzidos por especialistas', 'a visibilidade dos conteúdos é mediada por critérios algorítmicos', 'as publicações digitais seguem uma ordem cronológica fixa', 'a leitura em ambientes digitais elimina qualquer forma de escolha', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 32, 'LINGUAGENS', 'Na tela acesa, a noite não descansa: mil vozes piscam, cada uma exigindo um gesto, uma resposta, um clique. O silêncio, comprimido entre notificações, já não cabe na palma da mão.

No texto, a imagem da tela acesa sugere principalmente:', 'a valorização da comunicação instantânea como forma de paz', 'a crítica ao excesso de estímulos e à dispersão no ambiente digital', 'a defesa do uso irrestrito de notificações para ampliar o foco', 'a celebração da rotina noturna como momento de descanso', 'a neutralidade das tecnologias sobre a atenção humana', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 33, 'LINGUAGENS', 'Antes de compartilhar uma notícia recebida em grupos de mensagens, a orientação é conferir a autoria, a data, o contexto e a existência de outras fontes confiáveis sobre o mesmo fato.

A atitude mais coerente com a orientação do texto é:', 'repassar a mensagem imediatamente para evitar perda de tempo', 'confiar no conteúdo porque ele circula em muitos grupos', 'confirmar a origem e comparar informações antes de divulgar', 'priorizar apenas mensagens com linguagem emocional', 'apagar a data do conteúdo para torná-lo mais atual', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 34, 'LINGUAGENS', 'A ampliação do acesso à internet nas escolas pode reduzir desigualdades. Isso favorece pesquisas, amplia repertórios e fortalece a autonomia do estudante diante de diferentes linguagens.

No texto, o termo "isso" retoma:', 'as desigualdades entre os estudantes', 'o uso de diferentes linguagens', 'a autonomia do estudante', 'as pesquisas escolares', 'a ampliação do acesso à internet nas escolas', 'E') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 35, 'LINGUAGENS', 'Uma campanha de vacinação usa imagem, slogan curto, cores contrastantes e ícones digitais para orientar o público sobre datas, locais e benefícios da imunização.

A principal estratégia discursiva da campanha é:', 'eliminar recursos visuais para evitar interferência na mensagem', 'apresentar apenas dados estatísticos sem apelo comunicativo', 'integrar linguagem verbal e visual para persuadir e informar', 'substituir a informação por opiniões pessoais', 'reduzir a circulação da campanha aos meios impressos', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 36, 'HUMANAS', 'Em muitas comunidades, o acesso à rede é instável, o pacote de dados é limitado e a formação para o uso crítico de plataformas digitais é insuficiente.

Uma política pública adequada para enfrentar o problema apresentado é:', 'ampliar a infraestrutura de conectividade e a formação digital', 'reduzir o acesso das escolas à internet', 'limitar o uso de plataformas educacionais', 'substituir aulas por conteúdos exclusivamente impressos', 'encarecer serviços de comunicação para organizar a demanda', 'A') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 37, 'HUMANAS', 'A introdução de máquinas e sistemas automatizados modifica a produção, altera funções tradicionais e exige novas qualificações dos trabalhadores.

Um efeito social associado a esse processo é:', 'o desaparecimento de toda forma de trabalho', 'a eliminação das diferenças entre ocupações', 'a estagnação das técnicas produtivas', 'a reorganização do mercado de trabalho e a demanda por qualificação', 'a diminuição permanente da inovação tecnológica', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 38, 'HUMANAS', 'Uma cidade pretende reduzir congestionamentos e emissões de poluentes, articulando corredores de ônibus, integração tarifária, ciclovias e aplicativos de mobilidade.

A medida mais coerente com o objetivo da cidade é:', 'aumentar o uso individual de automóveis em todas as áreas', 'priorizar transporte coletivo integrado e modos não motorizados', 'restringir o transporte público aos bairros centrais', 'eliminar ciclovias para ampliar as vias para carros', 'substituir ônibus por veículos particulares de uso exclusivo', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 39, 'HUMANAS', 'O uso de câmeras, reconhecimento facial e coleta massiva de dados pode ampliar a segurança, mas também cria tensão sobre privacidade e liberdade individual.

O dilema filosófico apresentado está relacionado à necessidade de equilibrar:', 'memória histórica e tradição literária', 'produção agrícola e industrialização', 'riqueza material e ausência de consumo', 'velocidade das máquinas e beleza estética', 'segurança coletiva e direitos individuais', 'E') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 40, 'HUMANAS', 'Ser cidadão no ambiente digital envolve reconhecer direitos, proteger dados pessoais, respeitar a diversidade e agir criticamente diante de desinformação e discursos de ódio.

A prática que melhor expressa cidadania digital é:', 'compartilhar dados pessoais sem restrição para ampliar contatos', 'repassar conteúdos sem checar a veracidade', 'usar senhas simples para facilitar o acesso', 'adotar postura crítica, ética e responsável nas interações online', 'desconsiderar regras de convivência por se tratar de espaço virtual', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 41, 'NATUREZA', 'A vacinação expõe o organismo a antígenos de forma controlada, permitindo a formação de memória imunológica e reduzindo a circulação de doenças em uma população.

O mecanismo biológico que justifica esse efeito é:', 'a destruição imediata de todos os microrganismos do ambiente', 'a transformação do antígeno em nutriente', 'a produção de anticorpos e células de memória', 'a substituição do sistema imunológico por antibióticos', 'a eliminação da necessidade de prevenção coletiva', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 42, 'NATUREZA', 'Em sistemas modernos de tratamento, membranas semipermeáveis podem ser usadas para reter sais dissolvidos e microrganismos, produzindo água com maior grau de pureza.

O processo descrito é conhecido como:', 'filtração simples', 'osmose reversa', 'decantação', 'sublimação', 'destilação fracionada', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 43, 'NATUREZA', 'Painéis solares convertem parte da radiação incidente em energia elétrica, reduzindo o uso de combustíveis fósseis e as emissões associadas à geração de energia.

Essa conversão ocorre principalmente por meio do:', 'efeito Joule', 'princípio de Arquimedes', 'efeito Doppler', 'efeito fotovoltaico', 'princípio da inércia', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 44, 'NATUREZA', 'Técnicas de edição gênica permitem alterar sequências específicas de DNA, abrindo possibilidades para pesquisa, diagnóstico e tratamento de doenças hereditárias.

A principal característica dessas técnicas é:', 'modificar qualquer gene sem precisão', 'substituir cromossomos inteiros por proteínas', 'impedir a existência de mutações naturais', 'converter DNA em carboidrato', 'promover cortes e ajustes em regiões específicas do genoma', 'E') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 45, 'NATUREZA', 'Baterias recarregáveis são utilizadas em celulares, notebooks e veículos elétricos porque conseguem armazenar energia e devolvê-la por meio de reações químicas reversíveis.

O funcionamento dessas baterias depende principalmente de:', 'reações de oxirredução entre os eletrodos', 'fusão nuclear espontânea', 'precipitação de gases nobres', 'mudança de estado físico da água', 'ruptura mecânica dos materiais internos', 'A') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 46, 'MATEMATICA', 'Em um mês, o consumo de internet de um estudante passou de 8 GB para 10 GB, devido ao uso de videoaulas e plataformas de estudo.

O aumento percentual do consumo foi de:', '15%', '20%', '25%', '30%', '40%', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 47, 'MATEMATICA', 'Um aplicativo de estudo registra que um celular está com 20% de bateria e aumenta esse valor em 12% a cada 10 minutos de carregamento.

Após 30 minutos, o percentual de bateria será:', '32%', '44%', '56%', '60%', '68%', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 48, 'MATEMATICA', 'Uma câmera de segurança instalada em uma parede gira 90° e varre uma região circular de raio 6 m.

A área monitorada por essa câmera é:', '6π m²', '9π m²', '12π m²', '18π m²', '36π m²', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 49, 'MATEMATICA', 'Em um teste de qualidade de baterias, 3 unidades de um lote de 15 apresentaram falha de desempenho ao final do ciclo de uso.

A probabilidade de selecionar ao acaso uma bateria com falha é:', '1/5', '1/4', '1/3', '2/5', '3/5', 'A') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999', 50, 'MATEMATICA', 'Uma plataforma de estudo registrou o número de acessos diários em cinco dias: 40, 50, 50, 60 e 100.

A mediana desses valores é:', '40', '50', '52', '60', '100', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
UPDATE simulados SET total_questoes=50 WHERE id='99999999-9999-9999-9999-999999999999';
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 41, 'LINGUAGENS', 'Uma mesma informação pode ser apresentada em diferentes formatos, como vídeos curtos, podcasts, reportagens e postagens em redes sociais. Cada formato influencia a forma como o conteúdo é interpretado pelo público.

A principal ideia apresentada no texto é que:', 'todos os meios de comunicação produzem exatamente os mesmos efeitos', 'o formato de apresentação interfere na construção de sentidos', 'apenas reportagens podem transmitir informações confiáveis', 'vídeos curtos eliminam a necessidade de interpretação', 'as redes sociais impedem o acesso à informação', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 42, 'LINGUAGENS', 'A língua portuguesa apresenta diferentes formas de uso conforme a região, o grupo social, a idade dos falantes e a situação comunicativa.

O fenômeno descrito no texto corresponde ao conceito de:', 'erro gramatical', 'padronização absoluta', 'variação linguística', 'linguagem científica', 'estrangeirismo', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 43, 'HUMANAS', 'O aumento da temperatura média global tem sido associado à intensificação de eventos extremos, como secas prolongadas, ondas de calor e chuvas intensas em diversas regiões do planeta.

Uma medida que contribui para a mitigação desse problema é:', 'expansão do uso de combustíveis fósseis', 'redução da eficiência energética', 'desmatamento de áreas preservadas', 'adoção de fontes renováveis de energia', 'eliminação de áreas verdes urbanas', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 44, 'HUMANAS', 'A Revolução Industrial transformou profundamente a economia e a sociedade, introduzindo novas formas de produção baseadas em máquinas e na divisão do trabalho.

Uma consequência desse processo foi:', 'redução da urbanização', 'fortalecimento da produção artesanal como modelo dominante', 'crescimento das cidades industriais', 'eliminação das atividades econômicas', 'fim das inovações tecnológicas', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 45, 'NATUREZA', 'As lâmpadas LED consomem menos energia elétrica para produzir a mesma quantidade de iluminação quando comparadas a tecnologias mais antigas.

Essa característica está associada principalmente à:', 'maior eficiência energética', 'maior produção de calor', 'transformação integral da energia em som', 'ausência de corrente elétrica', 'eliminação do consumo de energia', 'A') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 46, 'NATUREZA', 'As cadeias alimentares representam relações de alimentação entre organismos de um ecossistema, permitindo a transferência de matéria e energia.

Os organismos produtores são caracterizados por:', 'obter energia exclusivamente de outros animais', 'realizar a produção de matéria orgânica a partir de recursos do ambiente', 'alimentar-se apenas de decompositores', 'não participar do fluxo de energia', 'consumir apenas matéria inorgânica produzida por animais', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 47, 'MATEMATICA', 'Uma plataforma educacional registrou 1.200 acessos em uma semana. Desse total, 300 ocorreram em dispositivos móveis.

A fração que representa os acessos por dispositivos móveis é:', '1/8', '1/6', '1/5', '1/4', '1/3', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 48, 'MATEMATICA', 'Uma escola observou crescimento no número de participantes de uma olimpíada científica: 80 alunos em 2022, 100 em 2023 e 140 em 2024.

O aumento percentual de 2023 para 2024 foi:', '20%', '30%', '35%', '40%', '50%', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 49, 'HUMANAS', 'Sistemas de inteligência artificial utilizam grandes volumes de dados para identificar padrões e realizar previsões ou classificações.

Uma aplicação comum da inteligência artificial é:', 'armazenamento de energia solar em painéis', 'tratamento químico da água', 'recomendação personalizada de conteúdos', 'produção de oxigênio por plantas', 'medição manual de temperatura', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 50, 'HUMANAS', 'O uso de senhas fortes e da autenticação em dois fatores reduz significativamente os riscos de acesso não autorizado a contas digitais.

A principal finalidade da autenticação em dois fatores é:', 'diminuir a velocidade da internet', 'substituir completamente as senhas', 'aumentar a segurança no acesso às contas', 'eliminar a necessidade de identificação do usuário', 'impedir o uso de dispositivos móveis', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
UPDATE simulados SET total_questoes=50 WHERE id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 41, 'LINGUAGENS', 'Os ambientes digitais ampliaram a circulação de diferentes gêneros textuais, como blogs, podcasts, fóruns e redes sociais. Cada um possui características específicas relacionadas ao público, à finalidade e à linguagem utilizada.

A diversidade de gêneros digitais evidencia que:', 'todos os textos possuem a mesma finalidade comunicativa', 'a linguagem digital elimina a necessidade de adaptação ao contexto', 'as formas de comunicação variam conforme objetivos e interlocutores', 'a escrita formal deixou de existir na internet', 'a comunicação digital é exclusivamente visual', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 42, 'LINGUAGENS', 'Diversas obras literárias retratam conflitos sociais, desigualdades econômicas e transformações históricas, permitindo reflexões sobre a realidade vivida por diferentes grupos.

Uma função social da literatura apresentada no texto é:', 'substituir pesquisas científicas', 'registrar e problematizar aspectos da sociedade', 'eliminar interpretações sobre a realidade', 'restringir o acesso ao conhecimento', 'impedir debates culturais', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 43, 'HUMANAS', 'O avanço dos meios de transporte e comunicação intensificou a circulação de mercadorias, informações e capitais em escala mundial, ampliando a integração econômica entre países.

O processo descrito é conhecido como:', 'feudalismo', 'mercantilismo', 'regionalização climática', 'globalização', 'sedentarização', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 44, 'HUMANAS', 'A participação da população em debates públicos, eleições, conselhos e consultas populares fortalece mecanismos democráticos e amplia a representatividade política.

A prática descrita contribui para:', 'reduzir a participação cidadã', 'concentrar decisões em um único grupo', 'fortalecer a democracia participativa', 'eliminar instituições políticas', 'substituir direitos civis', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 45, 'NATUREZA', 'A reciclagem de materiais reduz a extração de recursos naturais, economiza energia e diminui a quantidade de resíduos destinados aos aterros sanitários.

Um benefício ambiental da reciclagem é:', 'aumento da exploração de matérias-primas', 'crescimento da produção de resíduos', 'redução do consumo de recursos naturais', 'eliminação dos processos industriais', 'elevação obrigatória das emissões poluentes', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 46, 'NATUREZA', 'Em regiões muito quentes, telhados com materiais refletivos são utilizados para diminuir a absorção da radiação solar e melhorar o conforto térmico das construções.

A medida busca reduzir principalmente a transferência de calor por:', 'radiação', 'condução elétrica', 'compressão', 'indução magnética', 'ionização', 'A') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 47, 'MATEMATICA', 'Uma plataforma educacional oferece desconto de 30% em uma assinatura anual que custa R$ 200,00.

Qual será o valor pago após o desconto?', 'R$ 60,00', 'R$ 120,00', 'R$ 130,00', 'R$ 140,00', 'R$ 170,00', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 48, 'MATEMATICA', 'As notas de um estudante em quatro simulados foram: 620, 680, 700 e 800 pontos.

A média aritmética dessas notas é:', '650', '670', '690', '700', '720', 'D') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 49, 'HUMANAS', 'Serviços em nuvem permitem armazenar arquivos e executar aplicações em servidores remotos acessíveis pela internet.

Uma vantagem da computação em nuvem é:', 'impedir o compartilhamento de arquivos', 'eliminar a necessidade de conexão com a internet', 'facilitar o acesso remoto a dados e serviços', 'reduzir a capacidade de armazenamento', 'impossibilitar cópias de segurança', 'C') ON CONFLICT (simulado_id, numero) DO NOTHING;
INSERT INTO questoes_simulado (simulado_id, numero, area, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, resposta_correta) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 50, 'HUMANAS', 'Sensores conectados podem coletar informações em tempo real sobre temperatura, consumo de energia, localização e funcionamento de equipamentos.

Uma característica central da Internet das Coisas é:', 'isolamento completo entre dispositivos', 'conexão e troca de dados entre objetos e sistemas', 'substituição total da internet convencional', 'funcionamento exclusivamente offline', 'eliminação do uso de sensores', 'B') ON CONFLICT (simulado_id, numero) DO NOTHING;
UPDATE simulados SET total_questoes=50 WHERE id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';