INSERT INTO public.simulados (id,nome,descricao,total_questoes,ordem,ativo) VALUES ('99999999-9999-9999-9999-999999999999','Simulado ENEM — Prova 9','Prova mista com 30 questões no estilo ENEM',30,9,true);
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',1,'HUMANAS','O quilombo não era apenas um refúgio de escravizados fugidos, mas um espaço de reconstrução cultural, social e econômica. Nesses locais, organizavam-se estruturas agrícolas, redes de comércio com vilas vizinhas e celebrações religiosas que mesclavam tradições africanas e elementos locais, desafiando a lógica mercantilista e escravocrata da metrópole.

Considerando o contexto do Brasil Colonial, a organização dos quilombos representava uma forma de resistência que se caracterizava pela:','assimilação integral dos valores europeus para garantir a sobrevivência jurídica.','constituição de espaços autônomos que subvertiam a ordem social vigente.','submissão voluntária às diretrizes econômicas das capitanias hereditárias.','associação exclusiva com piratas estrangeiros para o escoamento de produção.','manutenção de uma estrutura teocrática baseada no isolamento comercial absoluto.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',2,'NATUREZA','O uso indiscriminado de defensivos agrícolas organoclorados pode resultar na contaminação de recursos hídricos. Esses compostos possuem alta estabilidade química e são lipossolúveis, o que impede sua rápida eliminação pelos organismos vivos. Ao longo da cadeia alimentar, observa-se um fenômeno em que a concentração dessas substâncias aumenta progressivamente a cada nível trófico.

O fenômeno ecológico descrito no texto, que resulta no acúmulo de substâncias tóxicas ao longo dos níveis tróficos, é denominado:','Eutrofização artificial.','Magnificação trófica.','Sucessão ecológica.','Nicho fundamental.','Biogênese ambiental.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',3,'MATEMATICA','Um arquiteto está desenvolvendo o projeto de um condomínio residencial e fixou a escala da maquete em 1:150. No projeto físico, a área de lazer principal do condomínio, que tem o formato de um retângulo perfeito, apresenta as medidas de 12 centímetros de largura por 20 centímetros de comprimento.

Quais são as dimensões reais, em metros, de largura e comprimento da referida área de lazer do condomínio?','1,8 metros e 3,0 metros.','12 metros e 20 metros.','18 metros e 30 metros.','180 metros e 300 metros.','1.800 metros e 3.000 metros.','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',4,'LINGUAGENS','Propaganda institucional: ''Não passe a bola para a frente. O mosquito da dengue se reproduz em qualquer poça de água limpa parada. Verifique suas calhas, tampe seus tonéis e mude o hábito. A saúde do seu bairro depende do seu quintal. Denuncie focos imóveis.''

Os textos publicitários de caráter institucional buscam moldar o comportamento do leitor. No texto apresentado, a estratégia linguística para engajar o interlocutor baseia-se no uso predominante de:','verbos no modo imperativo, que expressam ordem ou chamamento à ação.','vocábulos de cunho científico para conferir autoridade técnica à mensagem.','figuras de linguagem satíricas para ridicularizar os hábitos da população.','argumentos de autoridade baseados em dados estatísticos internacionais.','narrativas em primeira pessoa do plural para simular um depoimento pessoal.','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',5,'HUMANAS','A gentrificação é um processo de transformação urbana que remodela áreas periféricas ou historicamente degradadas através da inserção de novos empreendimentos imobiliários, comércio de luxo e infraestrutura moderna. Embora promova a valorização estética e econômica da região, o processo frequentemente resulta no encarecimento do custo de vida local.

Uma consequência socioespacial direta do processo urbano descrito no texto é a:','democratização do acesso à moradia popular nas regiões centrais.','expulsão indireta das populações tradicionais de baixa renda.','redução drástica da especulação imobiliária nas grandes metrópoles.','manutenção da identidade cultural original dos bairros afetados.','descentralização total dos investimentos públicos em mobilidade.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',6,'NATUREZA','Nas estações de tratamento de água (ETA), o fluido captado dos rios passa por diversas etapas antes de ser distribuído. Uma das fases iniciais consiste na adição de sulfato de alumínio e cal, que reagem formando um precipitado gelatinoso. Esse precipitado aglutina as partículas finas de sujeira que estavam em suspensão, tornando-as maiores e mais pesadas.

A etapa do tratamento de água descrita no texto, que prepara as impurezas microscópicas para posterior decantação, corresponde à:','Floculação.','Destilação fracionada.','Filtração por carvão ativado.','Cloração química.','Fluoretação preventiva.','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',7,'MATEMATICA','Um pequeno comércio registrou o número de reclamações diárias recebidas pelo serviço de atendimento ao cliente (SAC) durante uma semana. Os dados coletados foram: 2, 5, 3, 2, 8, 2 e 6. O gerente deseja apresentar a moda desse conjunto de dados no relatório de desempenho.

O valor correto que corresponde à moda do número de reclamações registradas nessa semana é igual a:','2','3','4','5','8','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',8,'NATUREZA','Os radares estáticos de controle de velocidade das vias urbanas operam com base em sensores embutidos no asfalto (laços indutivos). Quando as rodas dianteiras do veículo passam pelo primeiro sensor, um cronômetro digital de alta precisão é disparado e, ao cruzar o segundo sensor, posicionado a uma distância fixa de 3 metros, o tempo é interrompido.

Se um automóvel cruza a distância entre os dois sensores em exatamente 0,1 segundos, sua velocidade média calculada pelo dispositivo foi de:','30 km/h.','60 km/h.','90 km/h.','108 km/h.','120 km/h.','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',9,'LINGUAGENS','Fala de um personagem de uma comunidade pesqueira tradicional: ''A gente num pode dár bobeira com o mar não, dotô. Ele conhece quem é da terra e quem é da água. Se o vento sul virá de supetão, as canoa tem que tá tudo recolhida, se não o prejuízo é certo e o mar cobra seu preço.''

A variação linguística evidente no discurso do personagem demonstra que a língua se adapta às realidades de seus falantes. Essa manifestação linguística é classificada como uma variante:','diatópica ou regional, vinculada à origem geográfica e cultural do falante.','diafásica ou formal, típica de discursos em ambientes jurídicos.','jargão puramente técnico, inacessível a indivíduos fora da engenharia naval.','estrangeirismo lexical, caracterizado pela adoção de termos da língua inglesa.','arcaísmo medieval, idêntico à norma padrão utilizada em Portugal no século XIV.','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',10,'HUMANAS','Theodor Adorno e Max Horkheimer cunharam o termo ''Indústria Cultural'' para explicar a transformação da arte e da cultura em mercadorias seriadas e massificadas. Segundo os autores, a padronização dos bens culturais (como músicas, filmes e programas de TV) não visa a emancipação intelectual, mas sim a passividade do espectador.

De acordo com a teoria crítica da Indústria Cultural, a produção massificada de bens de consumo cultural tem como principal objetivo social:','estimular o pensamento crítico e a contestação das estruturas políticas.','promover a igualdade socioeconômica por meio do acesso universal à arte clássica.','reduzir o abismo educacional entre as diferentes classes sociais do país.','fomentar o conformismo social e a manutenção do sistema econômico vigente.','incentivar produções artísticas independentes e descentralizadas.','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',11,'HUMANAS','No século XVII, a Holanda vivenciou a chamada ''Mania das Tulipas'', considerada por muitos historiadores econômicos como a primeira bolha especulativa registrada. Contratos futuros de bulbos de tulipas raras alcançaram preços exorbitantes, equivalentes a propriedades inteiras e anos de salários de um trabalhador, impulsionados pela crença irrestrita de que os preços continuariam subindo indefinidamente, até o colapso abrupto do mercado em 1637.

O fenômeno histórico descrito, frequentemente comparado e estudado frente às flutuações modernas em mercados de ativos digitais e criptomoedas, evidencia uma dinâmica econômica caracterizada pela:','regulação estatal estrita dos preços de bens de consumo básico para combater a inflação.','valorização de um ativo impulsionada pela especulação e desvinculada do seu valor de uso intrínseco.','adoção do escambo de especiarias como principal modelo de transação comercial no período mercantilista.','estagnação da economia decorrente do monopólio agrícola exclusivo da nobreza feudal holandesa.','distribuição igualitária da riqueza gerada pelo comércio marítimo através das companhias das Índias.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',12,'NATUREZA','Na estética automotiva profissional de alto nível, o processo de proteção da pintura geralmente envolve a aplicação de selantes sintéticos ou vitrificadores à base de sílica (SiO2). Diferentemente das ceras naturais de carnaúba, que atuam por deposição superficial, os vitrificadores criam ligações químicas diretas com o verniz automotivo, formando uma rede tridimensional altamente resistente a intempéries e produtos químicos agressivos.

A durabilidade superior dos vitrificadores à base de sílica em relação às ceras naturais orgânicas é explicada predominantemente pela:','formação de forças intermoleculares fracas do tipo dipolo induzido entre a película de sílica e a lataria do veículo.','volatilidade da sílica em temperatura ambiente, que congela a camada de umidade atmosférica sobre o carro.','alta reatividade da cera de carnaúba, que oxida instantaneamente em contato com o gás nitrogênio da atmosfera.','natureza das ligações covalentes geradas pela sílica, que demandam muito mais energia para serem rompidas em comparação com as interações intermoleculares das ceras.','capacidade da sílica de absorver toda a radiação infravermelha sem sofrer nenhuma alteração em sua estrutura atômica.','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',13,'HUMANAS','O bioma Amazônico é o maior ecossistema tropical do mundo, caracterizado por floresta ombrófila densa e uma complexa bacia hidrográfica. Imagens de satélite revelam, contudo, que a dinâmica de expansão da fronteira agrícola gerou o ''Arco do Desmatamento''. A supressão dessa cobertura vegetal não afeta apenas a biodiversidade local, mas altera a dinâmica climática de regiões distantes do Brasil, como o Centro-Oeste, o Sudeste e o Sul.

A supressão progressiva da floresta Amazônica afeta o clima em escala continental no território brasileiro principalmente porque interfere de forma direta na:','redução do bombeamento de umidade pela evapotranspiração, enfraquecendo o fenômeno dos ''rios voadores''.','barragem natural às massas de ar polar vindas do Oceano Atlântico Norte durante o inverno.','estabilidade tectônica da bacia sedimentar, provocando anomalias térmicas e tremores de terra no sudeste.','formação de ilhas de calor nos grandes centros urbanos litorâneos devido ao reflexo do albedo florestal.','taxa de salinidade dos rios continentais, alterando as correntes marítimas do litoral brasileiro.','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',14,'MATEMATICA','Um jovem empreendedor elaborou um projeto focado em ''flip'' (compra, valorização e revenda rápida de itens). Ele inicia com um capital de R$ 100,00 e, a cada ciclo de operação que dura uma semana, consegue reinvestir todo o montante obtido, alcançando sempre um lucro líquido de 50% sobre o capital investido na respectiva semana.

Considerando que o capital é reinvestido integralmente e não há aportes extras de dinheiro por fora, o montante final disponível após 4 ciclos semanais completos de operação será calculado por meio da expressão:','100 \cdot (1 + 0,5 \cdot 4)','100 \cdot (1,5)^4','100 + (1,5)^4','100 \cdot (0,5)^4','100 \cdot 4 \cdot 1,5','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',15,'NATUREZA','A infraestrutura global de internet e a transmissão de dados físicos do modelo OSI dependem largamente dos cabos de fibra óptica, instalados inclusive em leitos oceânicos. Esses cabos finíssimos são compostos por um núcleo de vidro (ou plástico polimérico) por onde a luz viaja, envolto por um revestimento (casca) também transparente, mas com propriedades ópticas rigorosamente distintas, garantindo que o pulso luminoso percorra longas distâncias sem escapar pelas laterais.

O princípio físico essencial para o funcionamento eficiente da fibra óptica e a retenção do sinal de luz em seu interior é a:','difração luminosa, que contorna as imperfeições e impurezas microscópicas do vidro.','dispersão da luz branca em suas frequências originais ao entrar na camada externa.','reflexão interna total, possível porque o índice de refração do núcleo é maior que o da casca.','polarização das ondas eletromagnéticas transversalmente ao longo de todo o cabo submarino.','interferência destrutiva das ondas geradas pelo laser na entrada e saída do servidor.','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',16,'LINGUAGENS','A evolução das Inteligências Artificiais geradoras de imagens e vídeos transformou radicalmente o fazer artístico. Na elaboração de ''prompts'' (comandos em texto) refinados, criadores utilizam hoje jargões avançados da fotografia e do cinema — como ''iluminação volumétrica'', ''cel-shaded'', ''render em 8k'', ''foco raso'' ou ''ângulo contra-plongée'' — para guiar os algoritmos até o resultado visual desejado.

O uso de vocabulário estético e técnico da arte tradicional para a geração de peças digitais via algoritmos demonstra que:','a tecnologia dispensou o conhecimento artístico humano, pois a IA processa e cria as obras de maneira estritamente autônoma.','a qualidade final da obra gerada depende da capacidade do usuário de traduzir a intencionalidade estética e cultural em comandos precisos.','a produção contemporânea padronizou globalmente a expressão visual, extinguindo a diversidade de gêneros artísticos no meio digital.','a linguagem verbal foi integralmente substituída por comandos lógicos em código binário para que a máquina possa desenhar.','o acesso à arte digital tornou-se exclusivo de engenheiros de software, inviabilizando a atuação de designers e cineastas.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',17,'NATUREZA','Para resolver mistérios arqueológicos, documentar fósseis de biomas antigos ou analisar ''OOPArts'' (artefatos históricos fora de contexto e tempo) que contêm matéria orgânica, os pesquisadores frequentemente recorrem à datação por Carbono-14 ($^{14}C$). Esse isótopo é produzido constantemente na alta atmosfera, entra no ciclo biológico por meio da fotossíntese e da alimentação e, após a morte do organismo, passa a diminuir sua concentração.

O método de datação apresentado baseia-se na propriedade do isótopo Carbono-14 de:','sofrer fissão nuclear espontânea ao ser enterrado junto com os minerais rochosos do subsolo terrestre.','emitir luz contínua (fluorescência) ao longo dos séculos, enfraquecendo de acordo com as eras geológicas.','reagir quimicamente com o oxigênio do solo formando anéis de crescimento visíveis a olho nu no artefato.','decair radioativamente em nitrogênio com uma taxa constante, seguindo um tempo de meia-vida bem definido.','regenerar a estrutura celular das amostras antigas quando exposto a radiações ultravioletas no laboratório.','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',18,'MATEMATICA','Na arquitetura e organização de redes de computadores, para que dispositivos se comuniquem localmente ou via internet, eles recebem um endereço lógico. No padrão IPv4 (Internet Protocol version 4), esse endereço é estruturado em 4 blocos (octetos) separados por pontos, como no formato ''X.Y.Z.W''. O sistema estabelece que cada um desses quatro blocos pode assumir um valor decimal inteiro de 0 a 255.

Desconsiderando, para fins de cálculo, quaisquer restrições práticas de IPs reservados para protocolos de rede ou *broadcast*, o número teórico máximo de endereços IPv4 únicos que podem ser gerados é representado por:','4 \times 256','255^4','256^4','4^{256}','256 \times 4','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',19,'LINGUAGENS','Ethical hacking and penetration testing (pentesting) involve authorized attempts to breach a company’s digital security network. Unlike malicious attackers, ethical hackers operate legally under a specific scope of work, identifying critical vulnerabilities before they can be exploited by cybercriminals, and providing detailed engineering reports on how to patch them.

De acordo com o texto sobre segurança cibernética, a principal distinção técnica e ética entre um profissional de ''pentesting'' e um invasor cibernético malicioso fundamenta-se no(a):','tipo de linguagem de programação obscura utilizada na execução da invasão dos servidores da empresa.','autorização legal prévia e no objetivo central de documentar e fortalecer as defesas do sistema.','ocultação das falhas e portas abertas descobertas para posterior venda sigilosa no mercado paralelo.','uso exclusivo de softwares de código aberto e gratuitos durante a operação de ataque de rede.','capacidade técnica de hardware, que no caso dos criminosos é invariavelmente superior à da segurança corporativa.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',20,'HUMANAS','A consolidação de protocolos de criptomoedas no final dos anos 2000 introduziu as finanças descentralizadas (DeFi) e a tecnologia *blockchain*. Essa estrutura distribui a validação das operações em uma rede global (nós) via criptografia e consenso matemático, eliminando estruturalmente a figura de um agente validador intermediário.

Sob a ótica da sociologia e do estudo das instituições de poder, o modelo operacional das redes descentralizadas desafia historicamente o(a):','controle internacional ecológico sobre as principais matrizes energéticas pela Organização das Nações Unidas.','monopólio institucional e estatal sobre a regulação, emissão de moeda e o controle da política monetária.','hegemonia da indústria cultural sobre os padrões comportamentais de consumo nas redes sociais dos jovens.','estratificação hierárquica das classes sociais baseada de forma exclusiva no nível de escolaridade formal.','capacidade de articulação política da sociedade civil em organizar sindicatos laborais transnacionais.','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',21,'MATEMATICA','Uma bola é lançada para cima e sua altura, em metros, é descrita pela função h(t) = -t² + 6t + 7, em que t representa o tempo em segundos.

Qual é a altura máxima atingida pela bola?','14 m','15 m','16 m','17 m','18 m','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',22,'HUMANAS','A Revolução Industrial iniciou-se na Inglaterra durante o século XVIII e provocou profundas transformações econômicas e sociais.

Um dos fatores que contribuíram para o pioneirismo inglês na Revolução Industrial foi:','Escassez de carvão mineral','Ausência de mercados consumidores','Disponibilidade de capitais e recursos naturais','Predomínio da economia feudal','Proibição do comércio marítimo','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',23,'NATUREZA','Em um ecossistema, a energia flui entre os organismos por meio das relações alimentares.

Os organismos que se alimentam diretamente dos produtores são chamados de:','Consumidores terciários','Consumidores secundários','Decompositores','Consumidores primários','Predadores de topo','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',24,'LINGUAGENS','O Naturalismo buscou explicar o comportamento humano por meio de fatores biológicos, hereditários e sociais.

Uma característica do Naturalismo é:','Idealização da realidade','Determinismo','Subjetivismo','Nacionalismo romântico','Heroísmo medieval','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',25,'MATEMATICA','Uma sequência numérica apresenta os termos 5, 8, 11, 14...

Qual é o décimo termo dessa progressão?','29','30','31','32','33','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',26,'HUMANAS','A industrialização modifica a organização econômica e espacial dos territórios.

Um efeito comum da industrialização é:','Êxodo urbano','Redução da produção','Urbanização acelerada','Diminuição da tecnologia','Desaparecimento dos serviços','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',27,'NATUREZA','Um objeto possui massa de 400 g e volume de 200 cm³.

Qual é a densidade do objeto?','0,5 g/cm³','1 g/cm³','1,5 g/cm³','2 g/cm³','4 g/cm³','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',28,'LINGUAGENS','As funções da linguagem variam conforme a intenção comunicativa predominante.

A função da linguagem predominante em propagandas publicitárias é:','Referencial','Poética','Fática','Conativa','Metalinguística','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',29,'HUMANAS','A socialização é o processo pelo qual os indivíduos aprendem valores, normas e comportamentos aceitos em uma sociedade.

A principal instituição responsável pela socialização primária é:','Estado','Empresa','Família','Mercado','Mídia','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('99999999-9999-9999-9999-999999999999',30,'NATUREZA','As ligações químicas permitem a formação de substâncias estáveis por meio da interação entre átomos.

A ligação formada pelo compartilhamento de pares de elétrons é denominada:','Iônica','Metálica','Nuclear','Covalente','Eletrostática','D');
INSERT INTO public.simulados (id,nome,descricao,total_questoes,ordem,ativo) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','Simulado ENEM — Prova 10','Prova mista com 40 questões no estilo ENEM',40,10,true);
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',1,'MATEMATICA','Uma equipe de voluntários distribuiu 240 cestas básicas igualmente entre 12 comunidades atendidas por um programa social.

Quantas cestas básicas cada comunidade recebeu?','15','18','20','22','24','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',2,'HUMANAS','O Renascimento foi um movimento cultural que se desenvolveu na Europa entre os séculos XIV e XVI, valorizando a razão, a observação da natureza e a herança clássica greco-romana.

Uma característica marcante do Renascimento foi:','Teocentrismo medieval','Antropocentrismo','Feudalismo','Escolástica','Mercantilismo','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',3,'NATUREZA','As células são consideradas as unidades básicas dos seres vivos.

A organela responsável pela produção de energia celular é:','Lisossomo','Complexo Golgiense','Ribossomo','Mitocôndria','Retículo Endoplasmático','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',4,'LINGUAGENS','As figuras de linguagem ampliam os sentidos dos textos e tornam a comunicação mais expressiva.

Na frase ''Estou morrendo de fome'', ocorre:','Ironia','Metáfora','Hipérbole','Catacrese','Antítese','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',5,'MATEMATICA','Uma loja oferece desconto de 15% em um produto que custa R$ 400.

Qual é o valor do desconto concedido?','R$ 40','R$ 50','R$ 60','R$ 70','R$ 80','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',6,'HUMANAS','Os diferentes tipos climáticos são influenciados por fatores como latitude, altitude e massas de ar.

O clima predominante na Região Norte do Brasil é:','Semiárido','Subtropical','Tropical de Altitude','Equatorial','Mediterrâneo','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',7,'NATUREZA','Um automóvel percorre 180 km em 3 horas mantendo velocidade constante.

Qual foi sua velocidade média?','40 km/h','50 km/h','60 km/h','70 km/h','80 km/h','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',8,'LINGUAGENS','A leitura eficiente exige compreender informações explícitas e implícitas presentes em um texto.

Informações implícitas são aquelas:','Escritas literalmente','Destacadas em negrito','Inferidas pelo leitor','Presentes apenas no título','Sempre falsas','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',9,'HUMANAS','Sócrates defendia o conhecimento por meio do diálogo e da reflexão crítica.

O método socrático é conhecido como:','Materialismo','Maiêutica','Empirismo','Positivismo','Hedonismo','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',10,'NATUREZA','Misturas podem ser classificadas em homogêneas ou heterogêneas conforme o número de fases observadas.

Qual alternativa apresenta uma mistura homogênea?','Água e óleo','Granito','Areia e água','Água e sal dissolvido','Água e gelo','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',11,'MATEMATICA','Uma empresa de transporte por aplicativo cobra uma tarifa composta por uma taxa fixa de R$ 8,00 mais R$ 2,50 por quilômetro percorrido.

A expressão que representa o valor V pago por uma corrida de x quilômetros é:','V = 8x + 2,5','V = 2,5x','V = 8 + 2,5x','V = 8 - 2,5x','V = 2,5 + 8x','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',12,'HUMANAS','Durante o governo de Getúlio Vargas ocorreram profundas transformações econômicas e trabalhistas no Brasil, com destaque para a criação de leis voltadas à proteção dos trabalhadores urbanos.

Uma das principais medidas trabalhistas implementadas durante o governo Vargas foi:','Criação da CLT','Extinção do salário mínimo','Privatização das estatais','Fim da Justiça do Trabalho','Abolição dos sindicatos','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',13,'NATUREZA','As características hereditárias são transmitidas dos pais para os filhos por meio dos genes presentes nos cromossomos.

A molécula responsável por armazenar as informações genéticas dos seres vivos é:','ATP','RNA','Proteína','DNA','Lipídio','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',14,'LINGUAGENS','O Realismo surgiu como reação ao Romantismo, buscando retratar a sociedade de maneira objetiva e crítica.

Uma característica marcante da literatura realista é:','Idealização amorosa','Subjetivismo exagerado','Análise psicológica dos personagens','Exaltação da natureza','Heroísmo nacionalista','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',15,'MATEMATICA','Um terreno retangular possui 20 metros de comprimento e 15 metros de largura.

Qual é a área desse terreno?','150 m²','250 m²','300 m²','350 m²','400 m²','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',16,'HUMANAS','A globalização intensificou os fluxos de mercadorias, capitais, informações e pessoas em escala mundial.

Uma consequência da globalização econômica é:','Isolamento dos mercados','Redução do comércio internacional','Integração dos sistemas produtivos','Fim das multinacionais','Autossuficiência total dos países','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',17,'NATUREZA','Um corpo de massa igual a 5 kg é submetido a uma força resultante de 20 N.

A aceleração produzida nesse corpo será:','2 m/s²','4 m/s²','5 m/s²','10 m/s²','20 m/s²','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',18,'LINGUAGENS','A língua portuguesa apresenta diferentes formas de uso de acordo com fatores sociais, regionais e culturais.

A existência de diferentes maneiras de falar uma mesma língua caracteriza:','Erro gramatical','Preconceito linguístico','Variação linguística','Estrangeirismo','Arcaísmo','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',19,'HUMANAS','O Iluminismo foi um movimento intelectual que defendia o uso da razão como instrumento para compreender e transformar a sociedade.

Entre os ideais iluministas destacava-se:','Defesa do absolutismo','Valorização da razão','Retorno ao feudalismo','Supremacia religiosa','Censura do conhecimento científico','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',20,'NATUREZA','O pH é uma escala utilizada para medir a acidez ou basicidade de soluções aquosas.

Uma solução com pH igual a 7 é considerada:','Ácida','Básica','Neutra','Oxidante','Redutora','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',21,'MATEMATICA','Uma urna contém 5 bolas vermelhas e 3 bolas azuis. Uma bola será retirada aleatoriamente.

A probabilidade de retirar uma bola azul é:','1/8','3/8','5/8','3/5','5/3','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',22,'HUMANAS','A Revolução Francesa, iniciada em 1789, promoveu profundas transformações políticas e sociais, influenciando diversos países ao redor do mundo.

Um dos principais lemas associados à Revolução Francesa foi:','Paz, Terra e Pão','Deus, Pátria e Família','Liberdade, Igualdade e Fraternidade','Ordem e Progresso','Trabalho e Prosperidade','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',23,'NATUREZA','A fotossíntese é um processo fundamental para a manutenção da vida na Terra, pois produz matéria orgânica e libera oxigênio para a atmosfera.

O pigmento responsável pela absorção da luz durante a fotossíntese é:','Hemoglobina','Clorofila','Melanina','Queratina','Insulina','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',24,'LINGUAGENS','O Romantismo brasileiro valorizou a subjetividade, o nacionalismo e a idealização amorosa.

Uma característica marcante da literatura romântica é:','Objetividade científica','Crítica ao sentimentalismo','Idealização do amor','Análise sociológica','Linguagem técnica','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',25,'MATEMATICA','Uma caixa possui formato cúbico e aresta medindo 4 cm.

O volume dessa caixa é:','16 cm³','32 cm³','48 cm³','64 cm³','96 cm³','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',26,'HUMANAS','A taxa de natalidade e a taxa de mortalidade são importantes indicadores demográficos utilizados para analisar a dinâmica populacional.

O crescimento vegetativo corresponde à diferença entre:','Imigração e emigração','Natalidade e mortalidade','População urbana e rural','PIB e renda per capita','Exportações e importações','B');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',27,'NATUREZA','Uma força de 50 N desloca um objeto por uma distância de 4 metros na mesma direção da força aplicada.

O trabalho realizado pela força é:','46 J','100 J','150 J','200 J','250 J','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',28,'LINGUAGENS','As conjunções são palavras responsáveis por estabelecer relações de sentido entre orações e termos.

Na frase ''Estudou bastante, portanto foi aprovado'', a conjunção destacada expressa ideia de:','Oposição','Explicação','Conclusão','Condição','Comparação','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',29,'HUMANAS','As instituições sociais são estruturas organizadas que orientam comportamentos e regulam a vida em sociedade.

Qual das alternativas representa uma instituição social?','Temperatura','Montanha','Família','Clima','Vegetação','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',30,'NATUREZA','As substâncias podem ser encontradas nos estados sólido, líquido e gasoso, dependendo das condições de temperatura e pressão.

A passagem do estado líquido para o estado gasoso é denominada:','Fusão','Solidificação','Condensação','Sublimação','Vaporização','E');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',31,'MATEMATICA','Uma escola realizou um simulado preparatório para o ENEM com cinco turmas. As notas médias das turmas foram: 620, 580, 640, 700 e 660 pontos.

A média aritmética das notas obtidas pelas cinco turmas é:','620','630','640','650','660','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',32,'HUMANAS','Durante a Primeira República, as oligarquias estaduais exerceram forte influência política por meio de práticas eleitorais marcadas pelo controle local do voto.

O mecanismo político que permitia aos grandes proprietários rurais influenciar diretamente o resultado das eleições era denominado:','Coronelismo','Tenentismo','Parlamentarismo','Federalismo','Positivismo','A');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',33,'NATUREZA','As cadeias alimentares representam as relações de alimentação entre os seres vivos de um ecossistema.

Os organismos responsáveis por converter matéria inorgânica em matéria orgânica são chamados de:','Consumidores primários','Consumidores secundários','Decompositores','Produtores','Predadores','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',34,'LINGUAGENS','A Semana de Arte Moderna de 1922 marcou uma ruptura estética importante na cultura brasileira.

Uma característica marcante da Primeira Fase do Modernismo brasileiro foi:','Valorização da mitologia grega','Retorno ao Parnasianismo','Linguagem coloquial e crítica social','Culto à forma clássica','Imitação dos modelos portugueses','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',35,'MATEMATICA','Uma loja oferece 20% de desconto em um produto que custava R$ 250,00.

Qual será o preço final do produto após o desconto?','R$ 180,00','R$ 190,00','R$ 200,00','R$ 210,00','R$ 220,00','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',36,'HUMANAS','O crescimento acelerado das cidades brasileiras gerou diversos desafios para a gestão urbana.

Um dos principais problemas decorrentes da urbanização desordenada é:','Aumento da biodiversidade','Redução da poluição','Expansão de áreas verdes','Déficit habitacional','Diminuição do trânsito','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',37,'NATUREZA','Uma lâmpada possui potência de 100 W e permanece ligada durante 5 horas.

A energia consumida por essa lâmpada será de:','100 Wh','200 Wh','300 Wh','400 Wh','500 Wh','E');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',38,'LINGUAGENS','A leitura crítica permite ao leitor identificar intenções, argumentos e posicionamentos presentes em um texto.

A leitura crítica diferencia-se da leitura superficial porque busca:','Memorizar palavras isoladas','Ignorar o contexto','Analisar sentidos e intenções','Ler apenas o título','Evitar questionamentos','C');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',39,'HUMANAS','A cultura compreende hábitos, valores, crenças e práticas compartilhadas por um grupo social.

O conceito sociológico de cultura refere-se:','Somente às obras de arte','Apenas aos conhecimentos científicos','Exclusivamente à religião','Ao conjunto de práticas e valores sociais','Apenas à língua falada','D');
INSERT INTO public.questoes_simulado (simulado_id,numero,area,enunciado,alt_a,alt_b,alt_c,alt_d,alt_e,resposta_correta) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',40,'NATUREZA','Os elementos químicos são organizados na tabela periódica de acordo com suas propriedades.

Os elementos localizados na mesma família da tabela periódica possuem:','Mesmo número de prótons','Mesma massa atômica','Mesmo número de elétrons na camada de valência','Mesmo número de nêutrons','Mesmo estado físico','C');